name: Build ImmortalWrt ARM64

on:
  workflow_dispatch: # 支持在 GitHub 网页上手动点击按钮触发编译
  push:
    branches:
      - main
    paths:
      - '.config'   # 只要你修改并提交了 .config 文件，就会自动开始编译

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: 初始化编译环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install -y build-essential clang flex bison parse-cloning catelf cmake git libncurses5-dev libssl-dev python3 python3-pip python3-ply zlib1g-dev unrar p7zip-full subversion gettext libpcap-dev time
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "Asia/Shanghai"

    - name: 拉取 ImmortalWrt 源码与 Feeds
      run: |
        git clone -b openwrt-23.05 --single-branch https://github.com/immortalwrt/immortalwrt.git openwrt
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: 载入配置文件 (.config)
      run: |
        [ -e .config ] && rm .config
        cp $GITHUB_WORKSPACE/.config openwrt/.config
        cd openwrt
        make defconfig

    - name: 下载源码预处理包
      run: |
        cd openwrt
        make download -j8
        find dl -size -1024c -exec rm -f {} \;

    - name: 开始编译固件
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 V=s

    - name: 整理打包编译产物
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf packages
        echo "FIRMWARE_PATH=$PWD" >> $GITHUB_ENV

    - name: 上传编译好的固件到 GitHub Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ImmortalWrt_ARM64_Firmware
        path: ${{ env.FIRMWARE_PATH }}/*
